use sk_host;
#1.what is the total revenue generated by male vs female customers?;
select gender,sum(Purchase_Amount)as amount,count(customer_ID)as total from new_cb group by gender;
#2.which customer used a discount but still spent more than average purchase amount?
select customer_id,Purchase_Amount from new_cb where Discount_Applied='yes' and Purchase_Amount>=(select avg(Purchase_Amount)from new_cb);
#3.which are the top 5 products with the highest average review rating?
select Item_Purchased,round(avg(Review_Rating),2)from new_cb group by Item_Purchased order by avg(Review_Rating)desc limit 5 ;
#4.compare the avg purchase amount b/w standard and express shipping?
select round(avg(Purchase_Amount),2),Shipping_Type from new_cb where Shipping_Type in("Express","Standard") group by Shipping_Type ;
#5.do subscribed customers spend more ? compare average spend & total revenue b/w subscribers & non subscribers? 
select count(Customer_ID),round(avg(Purchase_Amount),2) as avg_spend,round(sum(Purchase_Amount),2) as tot_rev,Subscription_Status from new_cb group by Subscription_Status order by tot_rev,avg_spend desc;
#6.which 5 products have the highest % of purchase with discounts applied?
select Item_Purchased,max(Purchase_Amount) from new_cb where Discount_Applied="yes" group by Item_Purchased order by max(Purchase_Amount) desc limit 5;
#7.segment customer into new ,returning and loyal based on their total no of previous purchase &show the count of each segment?
with customer_type as (select Customer_ID,Previous_Purchases,
case
     when Previous_Purchases=1 then "new"
     when Previous_Purchases between 2 and 10 then "return"
     else "loyal"
     end as customer_segment
from new_cb)
select customer_segment,count(*)as "no of cust"
from customer_type
group by customer_segment;
#8.what are the top 3 most purchased product within each category?
with item_countS as(
select Category,Item_Purchased,
count(Customer_ID)as total_orders,
ROW_NUMBER()over(partition by category order by count(Customer_ID)desc)as item_rank
from new_cb
group by category,Item_Purchased
)
select item_rank,Category,Item_Purchased,total_orders
from item_counts
where item_rank<=3;
#9.Are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe?
select Subscription_Status,count(Customer_ID) as repeat_buyers  from new_cb
where Previous_Purchases >5
group by Subscription_Status;
#10.what is the revenue contribution of each age group?
select 
sum(Purchase_Amount),age
from new_cb
group by age
order by sum(Purchase_Amount) desc;




